--- 
behaviors: 
  AIDriver: 
    behavioral_cloning: 
      demo_path: Demos/AIDriverRight1.demo
      strength: 1.0
    hyperparameters: 
      batch_size: 256
      beta: 0.0005
      buffer_size: 10240
      epsilon: 0.2
      lambd: 0.99
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3
    max_steps: 1000000000
    network_settings: 
      hidden_units: 128
      normalize: false
      num_layers: 2
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 0.8
      gail: 
        demo_path: Demos/AIDriverRight1.demo
        strength: 1.0
    summary_freq: 100000
    time_horizon: 64
    trainer_type: ppo
